name: PR Test
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version}}
          cache: "npm"
      - name: "testing"
        run: |
          npm install
          npm test
        env:
          PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
