name: PR Test
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Percy Test
        uses: percy/exec-action@v0.3.1
        with:
          command: "run test"
        env:
          PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
