name: PR Test
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1.0.0
      - name: Install dependencies
        run: yarn
      - name: Install cli
        run: npm install @percy/cli
      - name: Percy test
        uses: percy/exec-action@master
        with:
          command: "percy exec -- wdio --base-url=https://www.saucedemo.com/"
        env:
          PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
